//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity2
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocVien
    {
        public HocVien()
        {
            this.HocPhis = new HashSet<HocPhi>();
        }
    
        public string MSHV { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Phai { get; set; }
        public string MaLop { get; set; }
    
        public virtual ICollection<HocPhi> HocPhis { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
